### ISSUE TITLE
报错error

### ISSUE THREAD

**Issue by berlinal** [SimonZeng7108/RBF-PINN#1]
Traceback (most recent call last):
  File "F:\PINN\RBF-PINN-master\5_Burgers_1D\main.py", line 64, in <module>
    model = RBF_DNN(dim_in=dim_in, dim_out=dim_out, hidden_layer_centres=hidden_layer_centres, ub=dataset.ub, lb=dataset.lb).to(device).to(torch.float64)
  File "F:\PINN\RBF-PINN-master\5_Burgers_1D\network.py", line 131, in __init__
    self.rbf_layers.append(RBF_Layer(ub, lb, dim_in, hidden_layer_centres[0], basis_func))
TypeError: RBF_Layer.__init__() missing 1 required positional argument: 'order_pol'

**Comment by Signed-B** [comment]
I have this issue as well. I have solved it by: 
- changing line 126 of network.py to: `def __init__(self, dim_in, dim_out, hidden_layer_centres=[50, 40, 30, 20], ub=0, lb=0, basis_func= rbf.gaussian, order_pol=None, activation=nn.Tanh()):`
- changing line 131 of network.py to: `self.rbf_layers.append(RBF_Layer(ub, lb, dim_in, hidden_layer_centres[0], basis_func, order_pol))`
